name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install flake8
      - run: flake8 .

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: python -m pytest --cov=recycling_manager --cov-report=term-missing -q
      - name: Notify Discord (success)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then echo "Webhook não configurado"; exit 0; fi
          STATUS_MSG="✅ Testes passaram em ${GITHUB_REPOSITORY} (commit ${GITHUB_SHA::7})\nAutor: ${GITHUB_ACTOR}\nBranch: ${GITHUB_REF_NAME}"
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"$STATUS_MSG\"}" "$DISCORD_WEBHOOK_URL"
      - name: Notify Discord (failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then echo "Webhook não configurado"; exit 0; fi
          STATUS_MSG="❌ Testes falharam em ${GITHUB_REPOSITORY} (commit ${GITHUB_SHA::7})\nAutor: ${GITHUB_ACTOR}\nBranch: ${GITHUB_REF_NAME}\nVer logs: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"$STATUS_MSG\"}" "$DISCORD_WEBHOOK_URL"

  docker:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/recycling-manager
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Notify Discord (success)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then echo "Webhook não configurado"; exit 0; fi
          STATUS_MSG="🚀 Docker build publicado em ${GITHUB_REPOSITORY} (commit ${GITHUB_SHA::7})\nAutor: ${GITHUB_ACTOR}\nBranch: ${GITHUB_REF_NAME}\nTags: ${TAGS:-sem tag}"
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"$STATUS_MSG\"}" "$DISCORD_WEBHOOK_URL"
      - name: Notify Discord (failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then echo "Webhook não configurado"; exit 0; fi
          STATUS_MSG="❌ Docker build falhou em ${GITHUB_REPOSITORY} (commit ${GITHUB_SHA::7})\nAutor: ${GITHUB_ACTOR}\nBranch: ${GITHUB_REF_NAME}\nVer logs: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"$STATUS_MSG\"}" "$DISCORD_WEBHOOK_URL"
